package com.minicad.step.model.product;

import com.minicad.step.model.base.StepEntity;
/**
 * Resolved SURFACE_CURVE_SWEPT_FACE_SOLID / SWEPT_FACE_SOLID.
 * A solid generated by sweeping a face along a curve trajectory.
 */
public record StepSweptFaceSolid(
    int id,
    String name,
    StepEntity sweptFace,
    StepEntity trajectory,
    String entityName
) implements StepEntity {}
