package com.minicad.step.model.product;

import com.minicad.step.model.base.StepEntity;
/**
 * Resolved EXTRUDED_FACE_SOLID.
 * A solid generated by extruding a face along a direction.
 */
public record StepExtrudedFaceSolid(
    int id,
    String name,
    StepEntity sweptFace,
    StepEntity position,
    StepEntity direction,
    Double depth
) implements StepEntity {}
