package com.minicad.step.model.product;

import com.minicad.step.model.base.StepEntity;
import java.util.Objects;
/**
 * Resolved REVOLVED_FACE_SOLID.
 * A solid generated by revolving a face around an axis.
 */
/**
 * Resolved REVOLVED_FACE_SOLID.
 * A solid generated by revolving a face around an axis.
 */
public final class StepRevolvedFaceSolid implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity sweptFace;
    private final StepEntity position;
    private final StepEntity axis;
    private final Double angle;

    public StepRevolvedFaceSolid(int id, String name, StepEntity sweptFace, StepEntity position, StepEntity axis, Double angle) {
        this.id = id;
        this.name = name;
        this.sweptFace = sweptFace;
        this.position = position;
        this.axis = axis;
        this.angle = angle;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getPosition() {
        return position;
    }

    public StepEntity getAxis() {
        return axis;
    }

    public Double getAngle() {
        return angle;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepRevolvedFaceSolid that = (StepRevolvedFaceSolid) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(sweptFace, that.sweptFace) && Objects.equals(position, that.position) && Objects.equals(axis, that.axis) && Objects.equals(angle, that.angle);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, sweptFace, position, axis, angle);
    }

    @Override
    public String toString() {
        return "StepRevolvedFaceSolid{" + "id=" + id + "name=" + name + "sweptFace=" + sweptFace + "position=" + position + "axis=" + axis + "angle=" + angle + "}";
    }
}
