package com.minicad.step.model.product;

import com.minicad.step.model.base.StepEntity;
import java.util.Objects;
/**
 * Resolved EXTRUDED_FACE_SOLID.
 * A solid generated by extruding a face along a direction.
 */
/**
 * Resolved EXTRUDED_FACE_SOLID.
 * A solid generated by extruding a face along a direction.
 */
public final class StepExtrudedFaceSolid implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity sweptFace;
    private final StepEntity position;
    private final StepEntity direction;
    private final Double depth;

    public StepExtrudedFaceSolid(int id, String name, StepEntity sweptFace, StepEntity position, StepEntity direction, Double depth) {
        this.id = id;
        this.name = name;
        this.sweptFace = sweptFace;
        this.position = position;
        this.direction = direction;
        this.depth = depth;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getPosition() {
        return position;
    }

    public StepEntity getDirection() {
        return direction;
    }

    public Double getDepth() {
        return depth;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptFace() { return getSweptFace(); }
    public StepEntity position() { return getPosition(); }
    public StepEntity direction() { return getDirection(); }
    public Double depth() { return getDepth(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepExtrudedFaceSolid that = (StepExtrudedFaceSolid) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(sweptFace, that.sweptFace) && Objects.equals(position, that.position) && Objects.equals(direction, that.direction) && Objects.equals(depth, that.depth);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, sweptFace, position, direction, depth);
    }

    @Override
    public String toString() {
        return "StepExtrudedFaceSolid{" + "id=" + id + "name=" + name + "sweptFace=" + sweptFace + "position=" + position + "direction=" + direction + "depth=" + depth + "}";
    }
}
