package com.minicad.step.model.product;

import com.minicad.step.model.base.StepEntity;
import java.util.Objects;
/**
 * Resolved SURFACE_CURVE_SWEPT_FACE_SOLID / SWEPT_FACE_SOLID.
 * A solid generated by sweeping a face along a curve trajectory.
 */
/**
 * Resolved SURFACE_CURVE_SWEPT_FACE_SOLID / SWEPT_FACE_SOLID.
 * A solid generated by sweeping a face along a curve trajectory.
 */
public final class StepSweptFaceSolid implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity sweptFace;
    private final StepEntity trajectory;
    private final String entityName;

    public StepSweptFaceSolid(int id, String name, StepEntity sweptFace, StepEntity trajectory, String entityName) {
        this.id = id;
        this.name = name;
        this.sweptFace = sweptFace;
        this.trajectory = trajectory;
        this.entityName = entityName;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getTrajectory() {
        return trajectory;
    }

    public String getEntityName() {
        return entityName;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptFace() { return getSweptFace(); }
    public StepEntity trajectory() { return getTrajectory(); }
    public String entityName() { return getEntityName(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepSweptFaceSolid that = (StepSweptFaceSolid) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(sweptFace, that.sweptFace) && Objects.equals(trajectory, that.trajectory) && Objects.equals(entityName, that.entityName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, sweptFace, trajectory, entityName);
    }

    @Override
    public String toString() {
        return "StepSweptFaceSolid{" + "id=" + id + "name=" + name + "sweptFace=" + sweptFace + "trajectory=" + trajectory + "entityName=" + entityName + "}";
    }
}
