package com.minicad.app;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.*;

class StepMeshExporterTest {

    private static final String MINIMAL_SQUARE = """
            ISO-10303-21;
            HEADER;
            ENDSEC;
            DATA;
            #1=CARTESIAN_POINT('P0',(0.0,0.0,0.0));
            #2=CARTESIAN_POINT('P1',(1.0,0.0,0.0));
            #3=CARTESIAN_POINT('P2',(1.0,1.0,0.0));
            #4=CARTESIAN_POINT('P3',(0.0,1.0,0.0));
            #10=DIRECTION('DZ',(0.0,0.0,1.0));
            #11=DIRECTION('DX',(1.0,0.0,0.0));
            #12=AXIS2_PLACEMENT_3D('AXIS',#1,#10,#11);
            #13=PLANE('PL0',#12);
            #20=VERTEX_POINT('V0',#1);
            #21=VERTEX_POINT('V1',#2);
            #22=VERTEX_POINT('V2',#3);
            #23=VERTEX_POINT('V3',#4);
            #30=DIRECTION('D1',(1.0,0.0,0.0));
            #31=VECTOR('VE1',#30,1.0);
            #32=LINE('L1',#1,#31);
            #33=DIRECTION('D2',(0.0,1.0,0.0));
            #34=VECTOR('VE2',#33,1.0);
            #35=LINE('L2',#2,#34);
            #36=DIRECTION('D3',(-1.0,0.0,0.0));
            #37=VECTOR('VE3',#36,1.0);
            #38=LINE('L3',#3,#37);
            #39=DIRECTION('D4',(0.0,-1.0,0.0));
            #40=VECTOR('VE4',#39,1.0);
            #41=LINE('L4',#4,#40);
            #50=EDGE_CURVE('E1',#20,#21,#32,.T.);
            #51=EDGE_CURVE('E2',#21,#22,#35,.T.);
            #52=EDGE_CURVE('E3',#22,#23,#38,.T.);
            #53=EDGE_CURVE('E4',#23,#20,#41,.T.);
            #60=ORIENTED_EDGE('OE1',$,$,#50,.T.);
            #61=ORIENTED_EDGE('OE2',$,$,#51,.T.);
            #62=ORIENTED_EDGE('OE3',$,$,#52,.T.);
            #63=ORIENTED_EDGE('OE4',$,$,#53,.T.);
            #70=EDGE_LOOP('LOOP',(#60,#61,#62,#63));
            #71=FACE_OUTER_BOUND('FOB',#70,.T.);
            #80=ADVANCED_FACE('F0',(#71),#13,.T.);
            #90=CLOSED_SHELL('CS',(#80));
            #100=MANIFOLD_SOLID_BREP('S0',#90);
            ENDSEC;
            END-ISO-10303-21;
            """;

    @Test
    void shouldExportObj() {
        String obj = StepMeshExporter.exportObj(MINIMAL_SQUARE);

        assertTrue(obj.contains("# Generated by MiniCAD"));
        assertTrue(obj.contains("v "));
        assertTrue(obj.contains("vn "));
        assertTrue(obj.contains("f "));

        // Count vertices, normals, faces
        long vCount = obj.lines().filter(l -> l.startsWith("v ")).count();
        long vnCount = obj.lines().filter(l -> l.startsWith("vn ")).count();
        long fCount = obj.lines().filter(l -> l.startsWith("f ")).count();

        assertTrue(vCount >= 3, "Should have at least 3 vertices, got " + vCount);
        assertTrue(vnCount >= 1, "Should have at least 1 normal, got " + vnCount);
        assertTrue(fCount >= 1, "Should have at least 1 face, got " + fCount);
    }

    @Test
    void shouldExportStlBinary() {
        byte[] stl = StepMeshExporter.exportStlBinary(MINIMAL_SQUARE);

        // STL binary: 80-byte header + 4-byte triangle count + 50 bytes per triangle
        assertTrue(stl.length > 84, "STL binary should be larger than header");

        // Check triangle count
        int triangleCount = ((stl[83] & 0xFF) << 24) | ((stl[82] & 0xFF) << 16)
                | ((stl[81] & 0xFF) << 8) | (stl[80] & 0xFF);
        assertTrue(triangleCount >= 1, "Should have at least 1 triangle, got " + triangleCount);

        // Verify size: 80 + 4 + (triangles * 50)
        int expectedSize = 80 + 4 + (triangleCount * 50);
        assertEquals(expectedSize, stl.length, "STL binary size should match expected");
    }

    @Test
    void shouldExportStlText() {
        String stl = StepMeshExporter.exportStlText(MINIMAL_SQUARE);

        assertTrue(stl.startsWith("solid MiniCAD"));
        assertTrue(stl.contains("endsolid MiniCAD"));
        assertTrue(stl.contains("facet normal"));
        assertTrue(stl.contains("outer loop"));
        assertTrue(stl.contains("vertex "));
        assertTrue(stl.contains("endloop"));
        assertTrue(stl.contains("endfacet"));
    }

    @Test
    void shouldExportObjForCsgBlock() {
        String stepText = """
                ISO-10303-21;
                HEADER;
                ENDSEC;
                DATA;
                #1=CARTESIAN_POINT('ORIGIN',(0.0,0.0,0.0));
                #2=DIRECTION('Z',(0.0,0.0,1.0));
                #3=DIRECTION('X',(1.0,0.0,0.0));
                #4=AXIS2_PLACEMENT_3D('AX',#1,#2,#3);
                #5=BLOCK('B',#4,1.0,2.0,3.0);
                ENDSEC;
                END-ISO-10303-21;
                """;

        String obj = StepMeshExporter.exportObj(stepText);
        assertTrue(obj.contains("v "));
        assertTrue(obj.contains("f "));
    }

    @Test
    void shouldExportObjForRealFile() throws IOException {
        // Use a small text-based STEP file from examples
        Path stepPath = Path.of("examples/minimal-square.step");
        if (Files.exists(stepPath)) {
            String stepText = Files.readString(stepPath);
            String obj = StepMeshExporter.exportObj(stepText);
            assertTrue(obj.contains("v "));
            assertTrue(obj.contains("f "));
        }
    }

    @Test
    void shouldExportStlBinaryForRealFile() throws IOException {
        Path stepPath = Path.of("examples/minimal-square.step");
        if (Files.exists(stepPath)) {
            String stepText = Files.readString(stepPath);
            byte[] stl = StepMeshExporter.exportStlBinary(stepText);
            assertTrue(stl.length > 84);
        }
    }

    @Test
    void shouldExportObjForTessellated() {
        String stepText = """
                ISO-10303-21;
                HEADER;
                ENDSEC;
                DATA;
                #1=CARTESIAN_POINT('P0',(0.0,0.0,0.0));
                #2=CARTESIAN_POINT('P1',(1.0,0.0,0.0));
                #3=CARTESIAN_POINT('P2',(0.5,1.0,0.0));
                #4=DIRECTION('Z',(0.0,0.0,1.0));
                #5=DIRECTION('X',(1.0,0.0,0.0));
                #6=AXIS2_PLACEMENT_3D('AX',#1,#4,#5);
                #7=PLANE('PL',#6);
                #8=POLY_LOOP('PL',(#1,#2,#3));
                #9=FACE_OUTER_BOUND('FOB',#8,.T.);
                #10=ADVANCED_FACE('F',(#9),#7,.T.);
                #11=CLOSED_SHELL('CS',(#10));
                #12=MANIFOLD_SOLID_BREP('S',#11);
                ENDSEC;
                END-ISO-10303-21;
                """;

        String obj = StepMeshExporter.exportObj(stepText);
        assertTrue(obj.contains("v "));
        assertTrue(obj.contains("f "));
    }
}
