package com.minicad.step.model;

/**
 * Marker interface for resolved STEP semantic entities.
 */
public sealed interface StepEntity permits StepCartesianPoint, StepDirection, StepVector,
        StepAxis1Placement, StepAxis2Placement2D, StepAxis2Placement3D, StepPoint, StepCurve, StepSurface,
        StepLine, StepPlane, StepCircle, StepEllipse, StepConicCurve, StepGeometricReplica, StepPolyline, StepOffsetCurve2D, StepOffsetCurve3D, StepOrientedCurve, StepOffsetSurface, StepCompositeCurveSegment, StepCompositeCurve, StepCompositeCurveOnSurface,
        StepSurfaceCurve, StepSeamCurve, StepGeometricSet, StepPointSet, StepBoundedCurve, StepBSplineCurve, StepBSplineCurveWithKnots, StepRationalBSplineCurve, StepPiecewiseBezierCurve, StepBezierCurve, StepUniformCurve, StepQuasiUniformCurve, StepSurfaceModel, StepBoundedSurface, StepBSplineSurface, StepBSplineSurfaceWithKnots, StepRationalBSplineSurface, StepPiecewiseBezierSurface, StepBezierSurface, StepUniformSurface, StepQuasiUniformSurface, StepCylindricalSurface,
        StepConicalSurface, StepToroidalSurface, StepDegenerateToroidalSurface, StepSphericalSurface, StepSurfaceOfLinearExtrusion, StepSurfaceOfRevolution, StepRectangularTrimmedSurface, StepCurveBoundedSurface, StepOrientedSurface,
        StepTrimmedCurve, StepTopologicalRepresentationItem, StepVertex, StepEdge, StepFace, StepPath, StepOpenPath, StepOrientedPath, StepSubpath, StepVertexPoint, StepEdgeCurve, StepSubedge, StepConnectedEdgeSet, StepEdgeBasedWireframeModel,
        StepOrientedEdge, StepLoop, StepFaceBound, StepFaceEntity, StepConnectedFaceSet, StepConnectedFaceSubSet, StepOpenShell, StepSurfacedOpenShell, StepOrientedOpenShell, StepVertexShell, StepWireShell,
        StepClosedShell, StepOrientedClosedShell, StepSolidModel, StepManifoldSolidBrep, StepBrepWithVoids, StepBooleanResult, StepBooleanClippingResult, StepCsgPrimitive, StepCsgSolid, StepSolidReplica, StepProfileDef, StepSweptAreaSolid, StepHalfSpaceSolid, StepBoxDomain, StepRepresentationContext, StepGeometricRepresentationContext,
        StepDimensionalExponents, StepNamedUnit, StepSiUnit, StepContextDependentUnit, StepConversionBasedUnit, StepConversionBasedUnitWithOffset, StepRepresentation, StepApplicationContext, StepProductContext, StepProduct,
        StepProductRelationship, StepProductDefinitionFormation, StepProductDefinitionFormationRelationship, StepProductDefinitionContext, StepProductDefinition, StepProductDefinitionRelationship, StepProductDefinitionRelationshipRelationship, StepRepresentationMap, StepSymbolRepresentationMap,
        StepProductDefinitionShape, StepCharacterizedObject, StepShapeAspect, StepShapeAspectOccurrence, StepShapeAspectRelationship, StepShapeDefinitionRepresentation, StepMeasureWithUnit, StepTypedMeasureWithUnit,
        StepShapeRepresentationRelationship, StepNextAssemblyUsageOccurrence,
        StepContextDependentShapeRepresentation, StepMappedItem, StepCartesianTransformationOperator, StepItemDefinedTransformation,
        StepRepresentationRelationship, StepRepresentationRelationshipWithTransformation, StepUncertaintyMeasureWithUnit,
        StepGlobalUnitAssignedContext, StepGlobalUncertaintyAssignedContext, StepColour, StepColourSpecification, StepColourRgb,
        StepGroup, StepGroupRelationship,
        StepDocumentType, StepDocument, StepDocumentRelationship, StepOrganization, StepOrganizationRelationship, StepPerson, StepPersonAndOrganization,
        StepCalendarDate, StepCoordinatedUniversalTimeOffset, StepLocalTime, StepDateAndTime,
        StepApprovalStatus, StepApproval, StepApprovalRole, StepApprovalPersonOrganization, StepApprovalDateTime,
        StepPersonAndOrganizationRole, StepDateRole, StepDateAssignment, StepAppliedDateAssignment,
        StepDateTimeRole, StepDateTimeAssignment,
        StepPersonAndOrganizationAssignment, StepAppliedPersonAndOrganizationAssignment,
        StepApprovalAssignment, StepAppliedApprovalAssignment, StepAppliedDateTimeAssignment,
        StepSecurityClassificationLevel, StepSecurityClassification,
        StepSecurityClassificationAssignment, StepAppliedSecurityClassificationAssignment,
        StepDocumentReference, StepAppliedDocumentReference,
        StepContractType, StepContract, StepContractAssignment, StepAppliedContractAssignment,
        StepCertificationType, StepCertification, StepCertificationAssignment, StepAppliedCertificationAssignment,
        StepEffectivity, StepProductDefinitionEffectivity,
        StepAddress, StepGeneralProperty, StepGeneralPropertyRelationship, StepDocumentUsageConstraint,
        StepLanguage, StepLanguageAssignment, StepAppliedLanguageAssignment,
        StepExternalSourceRelationship, StepExternalIdentificationAssignment, StepAppliedExternalIdentificationAssignment,
        StepProductCategory, StepProductCategoryRelationship, StepEffectivityRelationship,
        StepClassificationRole, StepClassificationAssignment, StepAppliedClassificationAssignment,
        StepIdentificationRole, StepIdentificationAssignment, StepAppliedIdentificationAssignment,
        StepNameAssignment, StepAppliedNameAssignment,
        StepDescriptionAttribute, StepNameAttribute, StepIdAttribute,
        StepExternalSource, StepExternallyDefinedItem,
        StepOrganizationRole, StepOrganizationAssignment, StepAppliedOrganizationAssignment,
        StepGroupAssignment, StepAppliedGroupAssignment,
        StepShellBasedSurfaceModel, StepFaceBasedSurfaceModel, StepShellBasedWireframeModel,
        StepCurveStyle, StepPointStyle, StepCharacterGlyphStyleStroke, StepCharacterGlyphStyleOutline, StepCharacterGlyphStyleOutlineWithCharacteristics, StepTextStyleForDefinedFont, StepTextStyle, StepTextStyleWithSpacing, StepTextStyleWithJustification, StepTextStyleWithMirror, StepTextStyleWithBoxCharacteristics, StepSymbolColour, StepSymbolStyle, StepPreDefinedItem, StepPreDefinedMarker, StepPreDefinedSymbol, StepPreDefinedPointMarkerSymbol, StepPreDefinedDimensionSymbol, StepPreDefinedGeometricalToleranceSymbol, StepPreDefinedTerminatorSymbol, StepPreDefinedSurfaceSideStyle, StepPreDefinedTextFont, StepDraughtingPreDefinedTextFont, StepPreDefinedCurveFont, StepDraughtingPreDefinedCurveFont, StepUserDefinedCurveFont, StepPreDefinedColour, StepDraughtingPreDefinedColour, StepUserDefinedMarker, StepUserDefinedTerminatorSymbol,
        StepFillAreaStyleColour, StepFillAreaStyle, StepSurfaceStyleFillArea, StepSurfaceStyleBoundary, StepSurfaceStyleControlGrid, StepSurfaceStyleSegmentationCurve, StepSurfaceStyleSilhouette, StepSurfaceStyleTransparent, StepSurfaceStyleReflectanceAmbient, StepSurfaceStyleReflectanceAmbientDiffuse, StepSurfaceStyleReflectanceAmbientDiffuseSpecular, StepSurfaceStyleParameterLine, StepSurfaceSideStyle,
        StepSurfaceStyleUsage, StepPresentationStyleAssignment, StepStyledItem, StepOverRidingStyledItem,
        StepPresentationLayerAssignment,
        StepAnnotationFillArea, StepAnnotationFillAreaOccurrence, StepAnnotationPlaceholderOccurrence, StepAnnotationPlane, StepAnnotationPointOccurrence, StepAnnotationCurveOccurrence, StepAnnotationSymbol, StepAnnotationSymbolOccurrence, StepAnnotationSubfigureOccurrence, StepDraughtingAnnotationOccurrence, StepTerminatorSymbol, StepAnnotationOccurrenceRelationship, StepLeaderCurve, StepProjectionCurve, StepDimensionCurve, StepAnnotationText, StepAnnotationTextCharacter, StepAnnotationTextOccurrence, StepGeometricCurveSet, StepDraughtingCallout, StepDraughtingCalloutRelationship, StepMeasureRepresentationItem, StepValueRepresentationItem,
        StepItemIdentifiedRepresentationUsage, StepChainBasedItemIdentifiedRepresentationUsage, StepChainBasedGeometricItemSpecificUsage, StepPmiRequirementItemAssociation, StepMechanicalDesignRequirementItemAssociation, StepPlacedTarget, StepDraughtingModelItemAssociation, StepDraughtingModelItemAssociationWithPlaceholder, StepGeometricItemSpecificUsage, StepPcurve, StepDegeneratePcurve, StepRepresentationItem, StepGeometricRepresentationItem,
        StepDescriptiveRepresentationItem, StepPropertyDefinition, StepPropertyDefinitionRelationship,
        StepPropertyDefinitionRepresentation, StepAbstractVariable, StepRowVariable, StepScalarVariable,
        StepAttributeAssertion, StepForwardChainingRulePremise, StepBackChainingRuleBody, StepActionPropertyRepresentation,
        StepContactRatioRepresentation, StepKinematicPropertyDefinitionRepresentation,
        StepKinematicPropertyMechanismRepresentation, StepKinematicPropertyRepresentationRelation,
        StepKinematicPropertyTopologyRepresentation, StepPlacedDatumTargetFeature,
        StepResourcePropertyRepresentation, StepDerivedUnitElement, StepDerivedUnit,
        StepApplicationProtocolDefinition, StepProductRelatedProductCategory, StepGeometricSurfaceSet,
        StepClothoid, StepIndexedPolyCurve, StepSurfaceOfConstantRadius, StepDegenerateCurve,
        StepEdgeWire, StepRectangularCompositeSurface, StepSurfacePatch,
        StepCompositeCurveOnSurface3D, StepLineSegment, StepOffsetSurface2,
        StepPolygonalBoundedHalfSpace, StepSubface,
        StepOrientedSubface, StepRectangleHollowProfileDef, StepCentreLineArcProfileDef,
        StepSweptDiskSolid, StepRuledSurface,
        StepCenteredCircleProfileDef, StepRevolvedAreaSolidTapered, StepExtrudedAreaSolidTapered,
        StepSurfaceCurveSweptAreaSolid, StepAdvancedBrep, StepComplexClippingResult,
        StepCompositeText, StepTextLiteral, StepTessellatedFaceSet, StepComposedText,
        StepNonManifoldSolidBrep,
        StepManifoldSurfaceModel, StepSurfacedEdgeCurve,
        StepGeometricTolerance, StepToleranceZoneForm, StepToleranceZone,
        StepConfigurationItem, StepDirectedDimensionalSize,
        StepConfigurationEffectivity, StepFeatureControlFrame,
        StepRunoutToleranceZone, StepMaterialDesignation,
        StepLayeredItem, StepColorSpecification, StepWithDescriptiveRepresentationItem,
        StepDatum, StepDatumFeature, StepDatumReference, StepDatumTarget,
        StepDimensionalSize, StepDimensionalLocation, StepShapeDimensionRepresentation,
        StepPlusMinusTolerance, StepToleranceValue, StepMeasureRepresentationItemWithUnit,
        StepMeasureQualification,
        StepCsgVolume, StepBlockVolume,
        StepAngularLocation, StepAngularSize,
        StepDatumReferenceCompartment, StepDatumReferenceElement, StepCommonDatum,
        StepCompositeShapeAspect,
        StepDesignedPartDesignVersion, StepMakeFromRelationship,
        StepExternallyDefinedHatchStyle, StepExternallyDefinedTileStyle,
        StepMakeFromFeature, StepMakeFromUsageOption, StepQuantifiedAssemblyComponentUsage,
        StepSpecifiedHigherUsageOccurrence, StepAlternateProductRelationship,
        StepProductDefinitionWithAssociatedDocuments, StepShapeAspectShapeRepresentation,
        StepMakeFromBuildAssembly, StepAssemblyComponentRelationship, StepDesignMakeFrom,
        StepInterpolatedConfigurationSegment, StepRangeDimensionalSize,
        StepSurfaceStyleRendering, StepSurfaceStyleRenderingWithProperties, StepRenderingProperties,
        StepLightSource, StepLightSourceAmbient, StepLightSourceDirectional,
        StepLightSourcePositional, StepLightSourceSpot,
        StepPresentationLayerUsage, StepCameraModelD2, StepCameraModelD3,
        StepCameraUsage, StepCameraImage, StepPlanarBox, StepPlanarExtent, StepViewVolume,
        StepMechanicalDesignShapeRepresentation,
        StepKinematicPair, StepKinematicJoint, StepKinematicLink, StepKinematicStructure,
        StepPersonAndOrganizationAddress, StepOrganizationAddress, StepPersonAddress,
        StepGeneralizedDatum,
        StepActionDirective, StepActionMethod, StepAction,
        StepActionRelationship, StepActionStatus {

    /**
     * Returns the original STEP instance id.
     *
     * @return instance id
     */
    int id();

    /**
     * Returns the optional STEP label/name field.
     *
     * @return label or empty string
     */
    String name();
}
