package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved SURFACE_CURVE_SWEPT_FACE_SOLID / SWEPT_FACE_SOLID.
 * A solid generated by sweeping a face along a curve trajectory.
 */
public final class StepSweptFaceSolid extends AbstractStepEntity {
    private final StepEntity sweptFace;
    private final StepEntity trajectory;
    private final String entityName;

    public StepSweptFaceSolid(int id, String name, StepEntity sweptFace, StepEntity trajectory, String entityName) {
        super(id, name);
        this.sweptFace = sweptFace;
        this.trajectory = trajectory;
        this.entityName = entityName;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getTrajectory() {
        return trajectory;
    }

    public String getEntityName() {
        return entityName;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptFace() { return getSweptFace(); }
    public StepEntity trajectory() { return getTrajectory(); }
    public String entityName() { return getEntityName(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("sweptFace", sweptFace);
        state.put("trajectory", trajectory);
        state.put("entityName", entityName);
        return state;
    }
}
