package com.minicad.step.model.geometry;

import com.minicad.step.model.core.base.StepEntity;
import java.util.Objects;
/**
 * Resolved SURFACE_OF_CONSTANT_RADIUS.
 * A surface generated by sweeping a curve along a circular path with constant radius.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param sweptSurface the surface being swept
 * @param radius constant radius of the sweep
 */
/**
 * Resolved SURFACE_OF_CONSTANT_RADIUS.
 * A surface generated by sweeping a curve along a circular path with constant radius.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param sweptSurface the surface being swept
 * @param radius constant radius of the sweep
 */
public final class StepSurfaceOfConstantRadius implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity sweptSurface;
    private final double radius;

    public StepSurfaceOfConstantRadius(int id, String name, StepEntity sweptSurface, double radius) {
        this.id = id;
        this.name = name;
        this.sweptSurface = sweptSurface;
        this.radius = radius;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getSweptSurface() {
        return sweptSurface;
    }

    public double getRadius() {
        return radius;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptSurface() { return getSweptSurface(); }
    public double radius() { return getRadius(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepSurfaceOfConstantRadius that = (StepSurfaceOfConstantRadius) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(sweptSurface, that.sweptSurface) && radius == that.radius;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, sweptSurface, radius);
    }

    @Override
    public String toString() {
        return "StepSurfaceOfConstantRadius{" + "id=" + id + "name=" + name + "sweptSurface=" + sweptSurface + "radius=" + radius + "}";
    }
}
