package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved SURFACE_OF_TRANSLATION.
 * A surface generated by translating a profile curve along a direction.
 */
public final class StepSurfaceOfTranslation extends AbstractStepEntity {
    private final StepEntity profile;
    private final StepEntity direction;

    public StepSurfaceOfTranslation(int id, String name, StepEntity profile, StepEntity direction) {
        super(id, name);
        this.profile = profile;
        this.direction = direction;
    }

    public StepEntity getProfile() {
        return profile;
    }

    public StepEntity getDirection() {
        return direction;
    }

    // Record-style accessors
    public StepEntity profile() { return getProfile(); }
    public StepEntity direction() { return getDirection(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("profile", profile);
        state.put("direction", direction);
        return state;
    }
}
