package com.minicad.step.model;

/**
 * Resolved SURFACE_OF_PROJECTION.
 * A surface generated by projecting a profile curve along a direction onto a plane.
 */
public record StepSurfaceOfProjection(
    int id,
    String name,
    StepEntity profile,
    StepEntity projectionDirection,
    StepEntity targetPlane
) implements StepEntity {}
