package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved RULED_SURFACE.
 * A surface generated by moving a straight line between two directrix curves.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param position placement defining the surface's local coordinate system
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public final class StepRuledSurface extends AbstractStepEntity {
    private final StepAxis2Placement3D position;
    private final StepEntity directrix1;
    private final StepEntity directrix2;

    public StepRuledSurface(int id, String name, StepAxis2Placement3D position, StepEntity directrix1, StepEntity directrix2) {
        super(id, name);
        this.position = position;
        this.directrix1 = directrix1;
        this.directrix2 = directrix2;
    }

    public StepAxis2Placement3D getPosition() {
        return position;
    }

    public StepEntity getDirectrix1() {
        return directrix1;
    }

    public StepEntity getDirectrix2() {
        return directrix2;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepAxis2Placement3D position() { return getPosition(); }
    public StepEntity directrix1() { return getDirectrix1(); }
    public StepEntity directrix2() { return getDirectrix2(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("position", position);
        state.put("directrix1", directrix1);
        state.put("directrix2", directrix2);
        return state;
    }
}
