package com.minicad.step.model;

/**
 * Resolved REVOLVED_FACE_SOLID.
 * A solid generated by revolving a face around an axis.
 */
public record StepRevolvedFaceSolid(
    int id,
    String name,
    StepEntity sweptFace,
    StepEntity position,
    StepEntity axis,
    Double angle
) implements StepEntity {}
