package com.minicad.step.model;

/**
 * Resolved SURFACE_OF_TRANSLATION.
 * A surface generated by translating a profile curve along a direction.
 */
public record StepSurfaceOfTranslation(
    int id,
    String name,
    StepEntity profile,
    StepEntity direction
) implements StepEntity {}
