package com.minicad.step.model;

/**
 * Resolved RULED_SURFACE.
 * A surface generated by moving a straight line between two directrix curves.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param position placement defining the surface's local coordinate system
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public record StepRuledSurface(
    int id,
    String name,
    StepAxis2Placement3D position,
    StepEntity directrix1,
    StepEntity directrix2) implements StepEntity {
}
