package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved SURFACE_OF_CONSTANT_RADIUS.
 * A surface generated by sweeping a curve along a circular path with constant radius.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param sweptSurface the surface being swept
 * @param radius constant radius of the sweep
 */
public final class StepSurfaceOfConstantRadius extends AbstractStepEntity {
    private final StepEntity sweptSurface;
    private final double radius;

    public StepSurfaceOfConstantRadius(int id, String name, StepEntity sweptSurface, double radius) {
        super(id, name);
        this.sweptSurface = sweptSurface;
        this.radius = radius;
    }

    public StepEntity getSweptSurface() {
        return sweptSurface;
    }

    public double getRadius() {
        return radius;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptSurface() { return getSweptSurface(); }
    public double radius() { return getRadius(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("sweptSurface", sweptSurface);
        state.put("radius", radius);
        return state;
    }
}
