package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved REVOLVED_FACE_SOLID.
 * A solid generated by revolving a face around an axis.
 */
public final class StepRevolvedFaceSolid extends AbstractStepEntity {
    private final StepEntity sweptFace;
    private final StepEntity position;
    private final StepEntity axis;
    private final Double angle;

    public StepRevolvedFaceSolid(int id, String name, StepEntity sweptFace, StepEntity position, StepEntity axis, Double angle) {
        super(id, name);
        this.sweptFace = sweptFace;
        this.position = position;
        this.axis = axis;
        this.angle = angle;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getPosition() {
        return position;
    }

    public StepEntity getAxis() {
        return axis;
    }

    public Double getAngle() {
        return angle;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptFace() { return getSweptFace(); }
    public StepEntity position() { return getPosition(); }
    public StepEntity axis() { return getAxis(); }
    public Double angle() { return getAngle(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("sweptFace", sweptFace);
        state.put("position", position);
        state.put("axis", axis);
        state.put("angle", angle);
        return state;
    }
}
