package com.minicad.step.model.geometry;

import com.minicad.step.model.core.base.StepEntity;
import java.util.Objects;
/**
 * Resolved SURFACE_OF_TRANSLATION.
 * A surface generated by translating a profile curve along a direction.
 */
/**
 * Resolved SURFACE_OF_TRANSLATION.
 * A surface generated by translating a profile curve along a direction.
 */
public final class StepSurfaceOfTranslation implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity profile;
    private final StepEntity direction;

    public StepSurfaceOfTranslation(int id, String name, StepEntity profile, StepEntity direction) {
        this.id = id;
        this.name = name;
        this.profile = profile;
        this.direction = direction;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getProfile() {
        return profile;
    }

    public StepEntity getDirection() {
        return direction;
    }

    // Record-style accessors
    public StepEntity profile() { return getProfile(); }
    public StepEntity direction() { return getDirection(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepSurfaceOfTranslation that = (StepSurfaceOfTranslation) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(profile, that.profile) && Objects.equals(direction, that.direction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, profile, direction);
    }

    @Override
    public String toString() {
        return "StepSurfaceOfTranslation{" + "id=" + id + "name=" + name + "profile=" + profile + "direction=" + direction + "}";
    }
}
