package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved EXTRUDED_FACE_SOLID.
 * A solid generated by extruding a face along a direction.
 */
public final class StepExtrudedFaceSolid extends AbstractStepEntity {
    private final StepEntity sweptFace;
    private final StepEntity position;
    private final StepEntity direction;
    private final Double depth;

    public StepExtrudedFaceSolid(int id, String name, StepEntity sweptFace, StepEntity position, StepEntity direction, Double depth) {
        super(id, name);
        this.sweptFace = sweptFace;
        this.position = position;
        this.direction = direction;
        this.depth = depth;
    }

    public StepEntity getSweptFace() {
        return sweptFace;
    }

    public StepEntity getPosition() {
        return position;
    }

    public StepEntity getDirection() {
        return direction;
    }

    public Double getDepth() {
        return depth;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepEntity sweptFace() { return getSweptFace(); }
    public StepEntity position() { return getPosition(); }
    public StepEntity direction() { return getDirection(); }
    public Double depth() { return getDepth(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("sweptFace", sweptFace);
        state.put("position", position);
        state.put("direction", direction);
        state.put("depth", depth);
        return state;
    }
}
