package com.minicad.step.model;

/**
 * Resolved SURFACE_OF_CONSTANT_RADIUS.
 * A surface generated by sweeping a curve along a circular path with constant radius.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param sweptSurface the surface being swept
 * @param radius constant radius of the sweep
 */
public record StepSurfaceOfConstantRadius(
    int id,
    String name,
    StepEntity sweptSurface,
    double radius) implements StepEntity {
}
