package com.minicad.step.model;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Resolved SURFACE_OF_PROJECTION.
 * A surface generated by projecting a profile curve along a direction onto a plane.
 */
public final class StepSurfaceOfProjection extends AbstractStepEntity {
    private final StepEntity profile;
    private final StepEntity projectionDirection;
    private final StepEntity targetPlane;

    public StepSurfaceOfProjection(int id, String name, StepEntity profile, StepEntity projectionDirection, StepEntity targetPlane) {
        super(id, name);
        this.profile = profile;
        this.projectionDirection = projectionDirection;
        this.targetPlane = targetPlane;
    }

    public StepEntity getProfile() {
        return profile;
    }

    public StepEntity getProjectionDirection() {
        return projectionDirection;
    }

    public StepEntity getTargetPlane() {
        return targetPlane;
    }

    // Record-style accessors
    public StepEntity profile() { return getProfile(); }
    public StepEntity projectionDirection() { return getProjectionDirection(); }

    @Override
    protected Map<String, Object> components() {
        Map<String, Object> state = new LinkedHashMap<>();
        state.put("id", getId());
        state.put("name", getName());
        state.put("profile", profile);
        state.put("projectionDirection", projectionDirection);
        state.put("targetPlane", targetPlane);
        return state;
    }
}
