package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.Preconditions;
import java.util.Objects;

/**
 * Minimal ruled surface representation.
 * A ruled surface is generated by moving a straight line along two directrix curves.
 *
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
/**
 * Minimal ruled surface representation.
 * A ruled surface is generated by moving a straight line along two directrix curves.
 *
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public final class RuledSurface3 implements SurfaceGeometry {
    private final Curve3 directrix1;
    private final Curve3 directrix2;

    public RuledSurface3(Curve3 directrix1, Curve3 directrix2) {
        this.directrix1 = directrix1;
        this.directrix2 = directrix2;
    }

    public Curve3 getDirectrix1() {
        return directrix1;
    }

    public Curve3 getDirectrix2() {
        return directrix2;
    }

    // Record-style accessors
    public Curve3 directrix1() { return getDirectrix1(); }
    public Curve3 directrix2() { return getDirectrix2(); }

    /**
     * Returns a point on the ruled surface at given parametric coordinates.
     *
     * @param u parameter along directrix curves (0 to 1)
     * @param v parameter between curves (0 to 1, 0 = directrix1, 1 = directrix2)
     * @return point on the surface
     */
    public CartesianPoint pointAt(double u, double v) {
        Preconditions.requireFinite(u, "u");
        Preconditions.requireFinite(v, "v");
        CartesianPoint p1 = directrix1.pointAt(u);
        CartesianPoint p2 = directrix2.pointAt(u);
        // Interpolate between p1 and p2
        return new CartesianPoint(
            p1.getX() + v * (p2.getX() - p1.getX()),
            p1.getY() + v * (p2.getY() - p1.getY()),
            p1.getZ() + v * (p2.getZ() - p1.getZ())
        );
    }

    /**
     * Returns the normal vector at a parametric position.
     *
     * @param u parameter along directrix curves
     * @param v parameter between curves
     * @return normal vector (approximate for general ruled surfaces)
     */
    public Vector3 normalAt(double u, double v) {
        // Approximate normal by computing tangent vectors
        // Tangent along u direction (along directrix)
        CartesianPoint pU0 = pointAt(Math.max(0, u - 0.01), v);
        CartesianPoint pU1 = pointAt(Math.min(1, u + 0.01), v);
        Vector3 tangentU = pU1.subtract(pU0);

        // Tangent along v direction (between directrices)
        CartesianPoint pV0 = pointAt(u, Math.max(0, v - 0.01));
        CartesianPoint pV1 = pointAt(u, Math.min(1, v + 0.01));
        Vector3 tangentV = pV1.subtract(pV0);

        // Normal is cross product of tangents
        return tangentU.cross(tangentV).normalize();
    }

    /**
     * Returns the bounding box of the ruled surface.
     *
     * @return bounding box
     */
    public BoundingBox3 boundingBox() {
        BoundingBox3 box1 = directrix1.boundingBox();
        BoundingBox3 box2 = directrix2.boundingBox();
        return box1.union(box2);
    }

    /**
     * Samples the ruled surface on a grid.
     *
     * @param uSegments number of segments along u direction
     * @param vSegments number of segments along v direction
     * @return list of sampled point rows
     */
    public java.util.List<java.util.List<CartesianPoint>> sampleGrid(int uSegments, int vSegments) {
        java.util.List<java.util.List<CartesianPoint>> grid = new java.util.ArrayList<>();
        for (int i = 0; i <= uSegments; i++) {
            java.util.List<CartesianPoint> row = new java.util.ArrayList<>();
            double u = (double) i / uSegments;
            for (int j = 0; j <= vSegments; j++) {
                double v = (double) j / vSegments;
                row.add(pointAt(u, v));
            }
            grid.add(java.util.List.copyOf(row));
        }
        return java.util.List.copyOf(grid);
    }

    /**
     * Finds the closest point on this surface to a given point.
     *
     * @param point the point to find closest point to
     * @return closest point on the surface
     */
    public CartesianPoint closestPointTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        // Sample grid and find closest point
        java.util.List<java.util.List<CartesianPoint>> grid = sampleGrid(32, 32);
        CartesianPoint closest = grid.get(0).get(0);
        double minDist = point.distanceTo(closest);
        for (java.util.List<CartesianPoint> row : grid) {
            for (CartesianPoint p : row) {
                double dist = point.distanceTo(p);
                if (dist < minDist) {
                    minDist = dist;
                    closest = p;
                }
            }
        }
        return closest;
    }

    /**
     * Computes the distance from a point to this surface.
     *
     * @param point the point to measure distance from
     * @return distance to the surface
     */
    public double distanceTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        CartesianPoint closest = closestPointTo(point);
        return point.distanceTo(closest);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RuledSurface3 that = (RuledSurface3) o;
        return Objects.equals(directrix1, that.directrix1) && Objects.equals(directrix2, that.directrix2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(directrix1, directrix2);
    }

    @Override
    public String toString() {
        return "RuledSurface3{" + "directrix1=" + directrix1 + "directrix2=" + directrix2 + "}";
    }
}
