package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.Preconditions;

/**
 * Minimal ruled surface representation.
 * A ruled surface is generated by moving a straight line along two directrix curves.
 *
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public record RuledSurface3(Curve3 directrix1, Curve3 directrix2) implements SurfaceGeometry {

    public RuledSurface3 {
        Preconditions.requireNonNull(directrix1, "directrix1");
        Preconditions.requireNonNull(directrix2, "directrix2");
    }

    /**
     * Evaluates a point on the ruled surface by interpolating between the two directrix curves.
     *
     * @param curveParameter parameter along both directrix curves
     * @param ruleParameter interpolation parameter (0 = directrix1, 1 = directrix2)
     * @return point on the surface
     */
    public CartesianPoint pointAt(double curveParameter, double ruleParameter) {
        Preconditions.requireFinite(curveParameter, "curveParameter");
        Preconditions.requireFinite(ruleParameter, "ruleParameter");
        CartesianPoint p1 = getPointOnCurve(directrix1, curveParameter);
        CartesianPoint p2 = getPointOnCurve(directrix2, curveParameter);
        Vector3 diff = p2.subtract(p1);
        return p1.add(diff.scale(ruleParameter));
    }

    private static CartesianPoint getPointOnCurve(Curve3 curve, double parameter) {
        if (curve instanceof BSplineCurve3 bspline) {
            return bspline.pointAt(parameter);
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.pointAt(parameter);
        } else if (curve instanceof Circle circle) {
            return circle.pointAt(parameter);
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.pointAt(parameter);
        } else if (curve instanceof Line3 line) {
            return line.pointAt(parameter);
        } else if (curve instanceof Polyline3 polyline) {
            return getPointOnPolyline(polyline, parameter);
        } else if (curve instanceof CompositeCurve3 composite) {
            return getPointOnComposite(composite, parameter);
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.pointAt(parameter);
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.pointAt(parameter);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.pointAt(parameter);
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return getPointOnCurve(surfaceCurve.curve3d(), parameter);
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.pointAt(parameter);
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.pointAt(parameter);
        }
        return new CartesianPoint(0, 0, 0);
    }

    private static CartesianPoint getPointOnPolyline(Polyline3 polyline, double parameter) {
        java.util.List<CartesianPoint> points = polyline.points();
        if (points.isEmpty()) {
            return new CartesianPoint(0, 0, 0);
        }
        int segments = points.size() - 1;
        double t = parameter * segments;
        int index = (int) Math.min(Math.floor(t), segments - 1);
        if (index < 0) index = 0;
        double localT = t - index;
        CartesianPoint p1 = points.get(index);
        CartesianPoint p2 = points.get(index + 1);
        return p1.add(p2.subtract(p1).scale(localT));
    }

    private static CartesianPoint getPointOnComposite(CompositeCurve3 composite, double parameter) {
        java.util.List<Curve3> segments = composite.segments();
        if (segments.isEmpty()) {
            return new CartesianPoint(0, 0, 0);
        }
        int index = (int) (parameter * segments.size());
        index = Math.max(0, Math.min(index, segments.size() - 1));
        double localT = parameter * segments.size() - index;
        return getPointOnCurve(segments.get(index), localT);
    }

    /**
     * Samples a patch on the ruled surface.
     *
     * @param curveSegments number of segments along the directrix curves
     * @param ruleSegments number of segments along the ruling direction
     * @return grid of sampled points
     */
    public java.util.List<java.util.List<CartesianPoint>> sampleGrid(int curveSegments, int ruleSegments) {
        java.util.List<CartesianPoint> samples1 = sampleCurve(directrix1, curveSegments);
        java.util.List<CartesianPoint> samples2 = sampleCurve(directrix2, curveSegments);
        if (samples1.isEmpty() || samples2.isEmpty()) {
            return java.util.List.of();
        }
        java.util.List<java.util.List<CartesianPoint>> grid = new java.util.ArrayList<>(curveSegments + 1);
        for (int i = 0; i <= curveSegments && i < samples1.size() && i < samples2.size(); i++) {
            CartesianPoint p1 = samples1.get(i);
            CartesianPoint p2 = samples2.get(i);
            java.util.List<CartesianPoint> column = new java.util.ArrayList<>(ruleSegments + 1);
            for (int j = 0; j <= ruleSegments; j++) {
                double t = (double) j / ruleSegments;
                column.add(p1.add(p2.subtract(p1).scale(t)));
            }
            grid.add(java.util.List.copyOf(column));
        }
        return java.util.List.copyOf(grid);
    }

    private static java.util.List<CartesianPoint> sampleCurve(Curve3 curve, int segments) {
        if (curve instanceof BSplineCurve3 bspline) {
            return bspline.sample(segments);
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.sample(segments);
        } else if (curve instanceof Circle circle) {
            return circle.sample(segments);
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.sample(segments);
        } else if (curve instanceof Line3 line) {
            return line.sample(segments, 0.0, 1.0);
        } else if (curve instanceof Polyline3 polyline) {
            return polyline.points();
        } else if (curve instanceof CompositeCurve3 composite) {
            return sampleCompositeCurve(composite, segments);
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.sample(segments);
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.sample(segments);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.sample(segments);
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return sampleCurve(surfaceCurve.curve3d(), segments);
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.sample(segments);
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.sample(segments);
        }
        return java.util.List.of();
    }

    private static java.util.List<CartesianPoint> sampleCompositeCurve(CompositeCurve3 composite, int segments) {
        java.util.List<CartesianPoint> allPoints = new java.util.ArrayList<>();
        int segmentsPerSegment = Math.max(1, segments / composite.segments().size());
        for (Curve3 segment : composite.segments()) {
            java.util.List<CartesianPoint> segmentPoints = sampleCurve(segment, segmentsPerSegment);
            allPoints.addAll(segmentPoints);
        }
        return java.util.List.copyOf(allPoints);
    }

    /**
     * Computes the normal at a given position on the ruled surface.
     * The normal is computed analytically from curve tangents and ruling direction.
     *
     * @param u parameter along the directrix curves
     * @param v interpolation parameter between directrices
     * @return unit normal vector
     */
    public Vector3 normalAt(double u, double v) {
        Preconditions.requireFinite(u, "u");
        Preconditions.requireFinite(v, "v");
        // For ruled surface R(u,v) = (1-v)*C1(u) + v*C2(u):
        // dR/du = (1-v)*C1'(u) + v*C2'(u)
        // dR/dv = C2(u) - C1(u)
        // normal = dR/du x dR/dv
        Vector3 t1 = curveTangent(directrix1, u);
        Vector3 t2 = curveTangent(directrix2, u);
        Vector3 tangentU = t1.scale(1.0 - v).add(t2.scale(v));
        CartesianPoint p1 = getPointOnCurve(directrix1, u);
        CartesianPoint p2 = getPointOnCurve(directrix2, u);
        Vector3 tangentV = p2.subtract(p1);
        if (tangentU.norm() <= Epsilon.EPS || tangentV.norm() <= Epsilon.EPS) {
            return new Vector3(0, 0, 1);
        }
        Vector3 normal = tangentU.cross(tangentV);
        if (normal.norm() <= Epsilon.EPS) {
            return new Vector3(0, 0, 1);
        }
        return normal.normalize().asVector();
    }

    private static Vector3 curveTangent(Curve3 curve, double parameter) {
        if (curve instanceof BSplineCurve3 bspline) {
            return bspline.tangentAt(parameter);
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.tangentAt(parameter);
        } else if (curve instanceof Circle circle) {
            return circle.tangentAt(parameter);
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.tangentAt(parameter);
        } else if (curve instanceof Line3 line) {
            return line.tangentAt(parameter);
        } else if (curve instanceof Polyline3 polyline) {
            return polyline.tangentAt(parameter);
        } else if (curve instanceof CompositeCurve3 composite) {
            return composite.tangentAt(parameter);
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.tangentAt(parameter);
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.tangentAt(parameter);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.tangentAt(parameter);
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return surfaceCurve.tangentAt(parameter);
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.tangentAt(parameter);
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.tangentAt(parameter);
        }
        // Fallback: numerical differentiation
        double eps = 0.001;
        CartesianPoint p1 = getPointOnCurve(curve, parameter - eps);
        CartesianPoint p2 = getPointOnCurve(curve, parameter + eps);
        Vector3 tangent = p2.subtract(p1);
        if (tangent.norm() <= Epsilon.EPS) {
            return new Vector3(1, 0, 0);
        }
        return tangent.normalize().asVector();
    }

    /**
     * Returns the bounding box for the ruled surface.
     *
     * @return bounding box enclosing both directrix curves
     */
    public BoundingBox3 boundingBox() {
        BoundingBox3 box1 = getCurveBoundingBox(directrix1);
        BoundingBox3 box2 = getCurveBoundingBox(directrix2);
        return box1.union(box2);
    }

    /**
     * Gets bounding box from curve.
     */
    private static BoundingBox3 getCurveBoundingBox(Curve3 curve) {
        if (curve instanceof Circle circle) {
            return circle.boundingBox();
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.boundingBox();
        } else if (curve instanceof Polyline3 polyline) {
            return polyline.boundingBox();
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.boundingBox();
        } else if (curve instanceof BSplineCurve3 bspline) {
            return bspline.boundingBox();
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.boundingBox();
        } else if (curve instanceof CompositeCurve3 composite) {
            return composite.boundingBox();
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return surfaceCurve.boundingBox();
        } else if (curve instanceof Line3 line) {
            return line.boundingBox(0.0, 1.0);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.boundingBox();
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.boundingBox();
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.boundingBox();
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.boundingBox();
        }
        // For other curves, sample and compute
        BoundingBox3 box = BoundingBox3.empty();
        java.util.List<CartesianPoint> samples = sampleCurve(curve, 64);
        for (CartesianPoint point : samples) {
            box = box.union(point);
        }
        return box;
    }

    /**
     * Returns the closest point on the ruled surface to a given point.
     * Uses sampling approach for ruled surfaces.
     *
     * @param point target point
     * @return approximate closest point on the ruled surface
     */
    public CartesianPoint closestPointTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        CartesianPoint closest = null;
        double minDistance = Double.POSITIVE_INFINITY;

        // Sample at multiple resolutions to find closest point
        for (int resolution : new int[]{16, 32, 64}) {
            java.util.List<java.util.List<CartesianPoint>> grid = sampleGrid(resolution, resolution);
            for (java.util.List<CartesianPoint> row : grid) {
                for (CartesianPoint sample : row) {
                    double dist = point.distanceTo(sample);
                    if (dist < minDistance) {
                        minDistance = dist;
                        closest = sample;
                    }
                }
            }
        }
        return closest != null ? closest : pointAt(0, 0);
    }

    /**
     * Returns the shortest distance from a point to the ruled surface.
     *
     * @param point target point
     * @return approximate shortest distance to the ruled surface
     */
    public double distanceTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        return point.distanceTo(closestPointTo(point));
    }
}