package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.Preconditions;
import java.util.Objects;

/**
 * Minimal ruled surface representation.
 * A ruled surface is generated by moving a straight line along two directrix curves.
 *
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
/**
 * Minimal ruled surface representation.
 * A ruled surface is generated by moving a straight line along two directrix curves.
 *
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public final class RuledSurface3 implements SurfaceGeometry {
    private final Curve3 directrix1;
    private final Curve3 directrix2;

    public RuledSurface3(Curve3 directrix1, Curve3 directrix2) {
        this.directrix1 = directrix1;
        this.directrix2 = directrix2;
    }

    public Curve3 getDirectrix1() {
        return directrix1;
    }

    public Curve3 getDirectrix2() {
        return directrix2;
    }

    // Record-style accessors
    public Curve3 directrix1() { return getDirectrix1(); }
    public Curve3 directrix2() { return getDirectrix2(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RuledSurface3 that = (RuledSurface3) o;
        return Objects.equals(directrix1, that.directrix1) && Objects.equals(directrix2, that.directrix2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(directrix1, directrix2);
    }

    @Override
    public String toString() {
        return "RuledSurface3{" + "directrix1=" + directrix1 + "directrix2=" + directrix2 + "}";
    }
}