package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.GeometryException;
import com.minicad.common.Preconditions;
import java.util.Objects;

/**
 * Minimal surface of projection representation.
 * Generated by projecting a profile curve along a direction.
 * Conceptually similar to extrusion: each point on the profile sweeps
 * along the projection direction to form the surface.
 *
 * @param profile profile curve to be projected
 * @param projectionDirection direction of projection
 */
/**
 * Minimal surface of projection representation.
 * Generated by projecting a profile curve along a direction.
 * Conceptually similar to extrusion: each point on the profile sweeps
 * along the projection direction to form the surface.
 *
 * @param profile profile curve to be projected
 * @param projectionDirection direction of projection
 */
public final class SurfaceOfProjection3 implements SurfaceGeometry {
    private final Curve3 profile;
    private final Vector3 projectionDirection;

    public SurfaceOfProjection3(Curve3 profile, Vector3 projectionDirection) {
        this.profile = profile;
        this.projectionDirection = projectionDirection;
    }

    public Curve3 getProfile() {
        return profile;
    }

    public Vector3 getProjectionDirection() {
        return projectionDirection;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SurfaceOfProjection3 that = (SurfaceOfProjection3) o;
        return Objects.equals(profile, that.profile) && Objects.equals(projectionDirection, that.projectionDirection);
    }

    @Override
    public int hashCode() {
        return Objects.hash(profile, projectionDirection);
    }

    @Override
    public String toString() {
        return "SurfaceOfProjection3{" + "profile=" + profile + "projectionDirection=" + projectionDirection + "}";
    }
}
