package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.GeometryException;
import com.minicad.common.Preconditions;
import java.util.Objects;

/**
 * Minimal surface of translation representation.
 * Generated by translating a profile curve along a direction vector.
 *
 * @param profile profile curve to be translated
 * @param direction translation direction vector
 */
/**
 * Minimal surface of translation representation.
 * Generated by translating a profile curve along a direction vector.
 *
 * @param profile profile curve to be translated
 * @param direction translation direction vector
 */
public final class SurfaceOfTranslation3 implements SurfaceGeometry {
    private final Curve3 profile;
    private final Vector3 direction;

    public SurfaceOfTranslation3(Curve3 profile, Vector3 direction) {
        this.profile = profile;
        this.direction = direction;
    }

    public Curve3 getProfile() {
        return profile;
    }

    public Vector3 getDirection() {
        return direction;
    }

    // Record-style accessors
    public Curve3 profile() { return getProfile(); }
    public Vector3 direction() { return getDirection(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SurfaceOfTranslation3 that = (SurfaceOfTranslation3) o;
        return Objects.equals(profile, that.profile) && Objects.equals(direction, that.direction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(profile, direction);
    }

    @Override
    public String toString() {
        return "SurfaceOfTranslation3{" + "profile=" + profile + "direction=" + direction + "}";
    }
}
