package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.GeometryException;
import com.minicad.common.Preconditions;

/**
 * Minimal surface of projection representation.
 * Generated by projecting a profile curve along a direction.
 * Conceptually similar to extrusion: each point on the profile sweeps
 * along the projection direction to form the surface.
 *
 * @param profile profile curve to be projected
 * @param projectionDirection direction of projection
 */
public record SurfaceOfProjection3(Curve3 profile, Vector3 projectionDirection) implements SurfaceGeometry {

    public SurfaceOfProjection3 {
        Preconditions.requireNonNull(profile, "profile");
        Preconditions.requireNonNull(projectionDirection, "projectionDirection");
        if (projectionDirection.norm() <= Epsilon.EPS) {
            throw new GeometryException("projectionDirection must be non-zero");
        }
    }

    /**
     * Evaluates a point on the projection surface.
     *
     * @param curveParameter parameter along the profile curve
     * @param projectionParameter parameter along the projection (0 to 1)
     * @return point on the surface
     */
    public CartesianPoint pointAt(double curveParameter, double projectionParameter) {
        Preconditions.requireFinite(curveParameter, "curveParameter");
        Preconditions.requireFinite(projectionParameter, "projectionParameter");
        CartesianPoint curvePoint = curveAt(profile, curveParameter);
        Vector3 offset = projectionDirection.scale(projectionParameter);
        return curvePoint.add(offset);
    }

    @Override
    public java.util.List<java.util.List<CartesianPoint>> sampleGrid(int curveSegments, int projectionSegments) {
        java.util.List<java.util.List<CartesianPoint>> grid = new java.util.ArrayList<>(curveSegments + 1);
        java.util.List<CartesianPoint> curveSamples = curveSamples(profile, curveSegments);
        if (curveSamples.isEmpty()) {
            return java.util.List.of();
        }
        for (CartesianPoint curvePoint : curveSamples) {
            java.util.List<CartesianPoint> column = new java.util.ArrayList<>(projectionSegments + 1);
            for (int j = 0; j <= projectionSegments; j++) {
                double t = (double) j / projectionSegments;
                column.add(curvePoint.add(projectionDirection.scale(t)));
            }
            grid.add(java.util.List.copyOf(column));
        }
        return java.util.List.copyOf(grid);
    }

    @Override
    public Vector3 normalAt(double curveParameter, double projectionParameter) {
        Preconditions.requireFinite(curveParameter, "curveParameter");
        Vector3 dir = projectionDirection.normalize().asVector();
        Vector3 curveTangent = curveTangentAt(profile, curveParameter);
        if (curveTangent.norm() <= Epsilon.EPS) {
            return dir.cross(new Vector3(1, 0, 0)).normalize().asVector();
        }
        Vector3 normal = curveTangent.cross(dir);
        if (normal.norm() <= Epsilon.EPS) {
            return dir.cross(new Vector3(0, 1, 0)).normalize().asVector();
        }
        return normal.normalize().asVector();
    }

    private static Vector3 curveTangentAt(Curve3 curve, double parameter) {
        if (curve instanceof BSplineCurve3 bspline) return bspline.tangentAt(parameter);
        if (curve instanceof RationalBSplineCurve3 rational) return rational.tangentAt(parameter);
        if (curve instanceof Circle circle) return circle.tangentAt(parameter);
        if (curve instanceof Ellipse3 ellipse) return ellipse.tangentAt(parameter);
        if (curve instanceof Parabola3 parabola) return parabola.tangentAt(parameter);
        if (curve instanceof Hyperbola3 hyperbola) return hyperbola.tangentAt(parameter);
        if (curve instanceof Clothoid3 clothoid) return clothoid.tangentAt(parameter);
        if (curve instanceof DegenerateCurve3 degenerate) return degenerate.tangentAt(parameter);
        if (curve instanceof Line3 line) return line.tangentAt(parameter);
        if (curve instanceof Polyline3 polyline) return polyline.tangentAt(parameter);
        if (curve instanceof TrimmedCurve3 trimmed) return trimmed.tangentAt(parameter);
        if (curve instanceof CompositeCurve3 composite) return composite.tangentAt(parameter);
        if (curve instanceof SurfaceCurve3 sc) return sc.tangentAt(parameter);
        // Fallback: numerical differentiation
        double eps = 0.001;
        CartesianPoint p1 = curveAt(curve, Math.max(0, parameter - eps));
        CartesianPoint p2 = curveAt(curve, parameter + eps);
        Vector3 tangent = p2.subtract(p1);
        if (tangent.norm() <= Epsilon.EPS) return new Vector3(1, 0, 0);
        return tangent.normalize().asVector();
    }

    @Override
    public BoundingBox3 boundingBox() {
        BoundingBox3 curveBox;
        if (profile instanceof Circle circle) {
            curveBox = circle.boundingBox();
        } else if (profile instanceof Ellipse3 ellipse) {
            curveBox = ellipse.boundingBox();
        } else if (profile instanceof Polyline3 polyline) {
            curveBox = polyline.boundingBox();
        } else if (profile instanceof BSplineCurve3 bspline) {
            curveBox = bspline.boundingBox();
        } else if (profile instanceof RationalBSplineCurve3 rational) {
            curveBox = rational.boundingBox();
        } else if (profile instanceof TrimmedCurve3 trimmed) {
            curveBox = trimmed.boundingBox();
        } else if (profile instanceof CompositeCurve3 composite) {
            curveBox = composite.boundingBox();
        } else if (profile instanceof SurfaceCurve3 surfaceCurve) {
            curveBox = surfaceCurve.curve3d().boundingBox();
        } else if (profile instanceof Line3 line) {
            curveBox = line.boundingBox(0.0, 1.0);
        } else if (profile instanceof Parabola3 parabola) {
            curveBox = parabola.boundingBox();
        } else if (profile instanceof Hyperbola3 hyperbola) {
            curveBox = hyperbola.boundingBox();
        } else if (profile instanceof Clothoid3 clothoid) {
            curveBox = clothoid.boundingBox();
        } else if (profile instanceof DegenerateCurve3 degenerate) {
            curveBox = degenerate.boundingBox();
        } else {
            curveBox = BoundingBox3.empty();
            for (CartesianPoint pt : curveSamples(profile, 64)) {
                curveBox = curveBox.union(pt);
            }
        }
        CartesianPoint end = curveBox.maxCorner().add(projectionDirection);
        return curveBox.union(end);
    }

    public CartesianPoint closestPointTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        CartesianPoint closest = null;
        double minDist = Double.POSITIVE_INFINITY;
        for (int res : new int[]{16, 32, 64}) {
            for (java.util.List<CartesianPoint> row : sampleGrid(res, res)) {
                for (CartesianPoint s : row) {
                    double d = point.distanceTo(s);
                    if (d < minDist) {
                        minDist = d;
                        closest = s;
                    }
                }
            }
        }
        return closest != null ? closest : pointAt(0, 0);
    }

    public double distanceTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        return point.distanceTo(closestPointTo(point));
    }

    private static CartesianPoint curveAt(Curve3 curve, double t) {
        if (curve instanceof BSplineCurve3 bspline) return bspline.pointAt(t);
        if (curve instanceof RationalBSplineCurve3 rational) return rational.pointAt(t);
        if (curve instanceof Circle circle) return circle.pointAt(t);
        if (curve instanceof Ellipse3 ellipse) return ellipse.pointAt(t);
        if (curve instanceof Parabola3 parabola) return parabola.pointAt(t);
        if (curve instanceof Hyperbola3 hyperbola) return hyperbola.pointAt(t);
        if (curve instanceof Clothoid3 clothoid) return clothoid.pointAt(t);
        if (curve instanceof DegenerateCurve3 degenerate) return degenerate.pointAt(t);
        if (curve instanceof Line3 line) return line.pointAt(t);
        if (curve instanceof Polyline3 polyline) return polyline.pointAt(t);
        if (curve instanceof TrimmedCurve3 trimmed) return trimmed.pointAt(t);
        if (curve instanceof CompositeCurve3 composite) return composite.pointAt(t);
        if (curve instanceof SurfaceCurve3 sc) return curveAt(sc.curve3d(), t);
        throw new GeometryException("unsupported profile curve type");
    }

    private static java.util.List<CartesianPoint> curveSamples(Curve3 curve, int segments) {
        if (curve instanceof BSplineCurve3 bspline) return bspline.sample(segments);
        if (curve instanceof RationalBSplineCurve3 rational) return rational.sample(segments);
        if (curve instanceof Circle circle) return circle.sample(segments);
        if (curve instanceof Ellipse3 ellipse) return ellipse.sample(segments);
        if (curve instanceof Parabola3 parabola) return parabola.sample(segments);
        if (curve instanceof Hyperbola3 hyperbola) return hyperbola.sample(segments);
        if (curve instanceof Clothoid3 clothoid) return clothoid.sample(segments);
        if (curve instanceof DegenerateCurve3 degenerate) return degenerate.sample(segments);
        if (curve instanceof Line3 line) return line.sample(segments, 0.0, 1.0);
        if (curve instanceof Polyline3 polyline) return polyline.points();
        if (curve instanceof TrimmedCurve3 trimmed) return trimmed.sample(segments);
        if (curve instanceof CompositeCurve3 composite) return composite.sample(segments);
        if (curve instanceof SurfaceCurve3 sc) return curveSamples(sc.curve3d(), segments);
        return java.util.List.of();
    }
}
