package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.GeometryException;
import com.minicad.common.Preconditions;

/**
 * Minimal surface of revolution representation.
 *
 * @param sweptCurve generatrix curve
 * @param axisOrigin point on revolution axis
 * @param axisDirection revolution axis direction
 */
public record SurfaceOfRevolution3(
        Curve3 sweptCurve,
        CartesianPoint axisOrigin,
        Direction3 axisDirection
) implements SurfaceGeometry {

    public SurfaceOfRevolution3 {
        Preconditions.requireNonNull(sweptCurve, "sweptCurve");
        Preconditions.requireNonNull(axisOrigin, "axisOrigin");
        Preconditions.requireNonNull(axisDirection, "axisDirection");
        if (axisDirection.asVector().norm() <= Epsilon.EPS) {
            throw new GeometryException("axisDirection must be greater than epsilon");
        }
    }

    /**
     * Evaluates a point on the surface of revolution.
     * The surface is generated by rotating the swept curve around the axis.
     *
     * @param curveParameter parameter along the swept curve
     * @param angle rotation angle in radians (0 to 2π)
     * @return point on the surface
     */
    public CartesianPoint pointAt(double curveParameter, double angle) {
        Preconditions.requireFinite(curveParameter, "curveParameter");
        Preconditions.requireFinite(angle, "angle");
        CartesianPoint curvePoint = getPointOnCurveInternal(sweptCurve, curveParameter);
        return rotatePointAroundAxis(curvePoint, angle);
    }

    /**
     * Gets a point on a curve at the given parameter.
     */
    private static CartesianPoint getPointOnCurveInternal(Curve3 curve, double parameter) {
        if (curve instanceof BSplineCurve3 bspline) {
            return bspline.pointAt(parameter);
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.pointAt(parameter);
        } else if (curve instanceof Circle circle) {
            return circle.pointAt(parameter);
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.pointAt(parameter);
        } else if (curve instanceof Line3 line) {
            return line.pointAt(parameter);
        } else if (curve instanceof Polyline3 polyline) {
            return getPointOnPolyline(polyline, parameter);
        } else if (curve instanceof CompositeCurve3 composite) {
            return getPointOnCompositeInternal(composite, parameter);
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            // For TrimmedCurve, interpolate between trim points
            return interpolatePoint(trimmed.trimStart(), trimmed.trimEnd(), parameter);
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.pointAt(parameter);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.pointAt(parameter);
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return getPointOnCurveInternal(surfaceCurve.curve3d(), parameter);
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.pointAt(parameter);
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.pointAt(parameter);
        }
        throw new GeometryException("unsupported swept curve type for point evaluation");
    }

    private static CartesianPoint getPointOnPolyline(Polyline3 polyline, double parameter) {
        java.util.List<CartesianPoint> points = polyline.points();
        if (points.isEmpty()) {
            return new CartesianPoint(0, 0, 0);
        }
        int segments = points.size() - 1;
        double t = parameter * segments;
        int index = (int) Math.min(Math.floor(t), segments - 1);
        if (index < 0) index = 0;
        double localT = t - index;
        CartesianPoint p1 = points.get(index);
        CartesianPoint p2 = points.get(index + 1);
        return p1.add(p2.subtract(p1).scale(localT));
    }

    private static CartesianPoint getPointOnCompositeInternal(CompositeCurve3 composite, double parameter) {
        java.util.List<Curve3> segments = composite.segments();
        if (segments.isEmpty()) {
            return new CartesianPoint(0, 0, 0);
        }
        int index = (int) (parameter * segments.size());
        index = Math.max(0, Math.min(index, segments.size() - 1));
        double localT = parameter * segments.size() - index;
        return getPointOnCurveInternal(segments.get(index), localT);
    }

    private static CartesianPoint interpolatePoint(CartesianPoint start, CartesianPoint end, double t) {
        return new CartesianPoint(
            start.x() + (end.x() - start.x()) * t,
            start.y() + (end.y() - start.y()) * t,
            start.z() + (end.z() - start.z()) * t
        );
    }

    /**
     * Rotates a point around the axis by the given angle.
     */
    private CartesianPoint rotatePointAroundAxis(CartesianPoint point, double angle) {
        Vector3 rel = point.subtract(axisOrigin);
        Vector3 axisVec = axisDirection.asVector();
        double axialComponent = rel.dot(axisVec);
        Vector3 axialPart = axisVec.scale(axialComponent);
        Vector3 radialPart = rel.subtract(axialPart);
        double radialLength = radialPart.norm();
        Vector3 perpDir = axisVec.cross(radialPart);
        if (perpDir.norm() <= Epsilon.EPS) {
            return point;
        }
        perpDir = perpDir.normalize().asVector();
        Vector3 rotatedRadial = radialPart.scale(Math.cos(angle)).add(perpDir.scale(radialLength * Math.sin(angle)));
        return axisOrigin.add(axialPart).add(rotatedRadial);
    }

    /**
     * Samples a patch on the surface of revolution.
     *
     * @param curveSegments number of segments along the swept curve
     * @param angleSegments number of segments around the revolution (full 2π)
     * @return grid of sampled points
     */
    public java.util.List<java.util.List<CartesianPoint>> sampleGrid(int curveSegments, int angleSegments) {
        java.util.List<java.util.List<CartesianPoint>> grid = new java.util.ArrayList<>(curveSegments + 1);
        java.util.List<CartesianPoint> curveSamples = sampleCurveInternal(sweptCurve, curveSegments);
        if (curveSamples.isEmpty()) {
            return java.util.List.of();
        }
        for (int i = 0; i < curveSamples.size(); i++) {
            CartesianPoint curvePoint = curveSamples.get(i);
            java.util.List<CartesianPoint> column = new java.util.ArrayList<>(angleSegments + 1);
            for (int j = 0; j <= angleSegments; j++) {
                double angle = 2.0 * Math.PI * j / angleSegments;
                column.add(rotatePointAroundAxis(curvePoint, angle));
            }
            grid.add(java.util.List.copyOf(column));
        }
        return java.util.List.copyOf(grid);
    }

    private static java.util.List<CartesianPoint> sampleCurveInternal(Curve3 curve, int segments) {
        if (curve instanceof BSplineCurve3 bspline) {
            return bspline.sample(segments);
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.sample(segments);
        } else if (curve instanceof Circle circle) {
            return circle.sample(segments);
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.sample(segments);
        } else if (curve instanceof Line3 line) {
            return line.sample(segments, 0.0, 1.0);
        } else if (curve instanceof Polyline3 polyline) {
            return polyline.points();
        } else if (curve instanceof CompositeCurve3 composite) {
            return sampleCompositeCurveInternal(composite, segments);
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.sample(segments);
        } else if (curve instanceof Hyperbola3 hyperbola) {
            return hyperbola.sample(segments);
        } else if (curve instanceof Parabola3 parabola) {
            return parabola.sample(segments);
        } else if (curve instanceof SurfaceCurve3 surfaceCurve) {
            return sampleCurveInternal(surfaceCurve.curve3d(), segments);
        } else if (curve instanceof Clothoid3 clothoid) {
            return clothoid.sample(segments);
        } else if (curve instanceof DegenerateCurve3 degenerate) {
            return degenerate.sample(segments);
        }
        return java.util.List.of();
    }

    private static java.util.List<CartesianPoint> sampleCompositeCurveInternal(CompositeCurve3 composite, int segments) {
        java.util.List<CartesianPoint> allPoints = new java.util.ArrayList<>();
        int segmentsPerSegment = Math.max(1, segments / composite.segments().size());
        for (Curve3 segment : composite.segments()) {
            java.util.List<CartesianPoint> segmentPoints = sampleCurveInternal(segment, segmentsPerSegment);
            allPoints.addAll(segmentPoints);
        }
        return java.util.List.copyOf(allPoints);
    }

    /**
     * Computes the normal at a given position on the revolution surface.
     * The normal is radial from the axis to the surface point.
     *
     * @param curveParameter parameter along the swept curve
     * @param angle rotation angle in radians
     * @return unit normal vector (radial from axis)
     */
    public Vector3 normalAt(double curveParameter, double angle) {
        Preconditions.requireFinite(curveParameter, "curveParameter");
        Preconditions.requireFinite(angle, "angle");
        CartesianPoint point = pointAt(curveParameter, angle);
        Vector3 rel = point.subtract(axisOrigin);
        Vector3 axisVec = axisDirection.asVector();
        double axialComponent = rel.dot(axisVec);
        Vector3 axialPart = axisVec.scale(axialComponent);
        Vector3 radialPart = rel.subtract(axialPart);
        if (radialPart.norm() <= Epsilon.EPS) {
            return axisVec;
        }
        return radialPart.normalize().asVector();
    }

    /**
     * Returns the bounding box for the revolution surface.
     *
     * @return bounding box enclosing the revolution surface
     */
    public BoundingBox3 boundingBox() {
        // Get bounding box of swept curve
        BoundingBox3 curveBox = getCurveBoundingBox(sweptCurve);
        // Revolution surface extends radially from axis
        // Find maximum radial extent from axis
        double maxRadialExtent = findMaxRadialExtent();
        return curveBox.expand(maxRadialExtent);
    }

    /**
     * Gets bounding box from curve.
     */
    private static BoundingBox3 getCurveBoundingBox(Curve3 curve) {
        if (curve instanceof Circle circle) {
            return circle.boundingBox();
        } else if (curve instanceof Ellipse3 ellipse) {
            return ellipse.boundingBox();
        } else if (curve instanceof Polyline3 polyline) {
            return polyline.boundingBox();
        } else if (curve instanceof TrimmedCurve3 trimmed) {
            return trimmed.boundingBox();
        } else if (curve instanceof BSplineCurve3 bspline) {
            return bspline.boundingBox();
        } else if (curve instanceof RationalBSplineCurve3 rational) {
            return rational.boundingBox();
        } else if (curve instanceof CompositeCurve3 composite) {
            return composite.boundingBox();
        }
        // For other curves, sample and compute
        BoundingBox3 box = BoundingBox3.empty();
        java.util.List<CartesianPoint> samples = sampleCurveInternal(curve, 64);
        for (CartesianPoint point : samples) {
            box = box.union(point);
        }
        return box;
    }

    /**
     * Finds the maximum radial extent of the swept curve from the axis.
     */
    private double findMaxRadialExtent() {
        java.util.List<CartesianPoint> samples = sampleCurveInternal(sweptCurve, 32);
        double maxRadial = 0.0;
        Vector3 axisVec = axisDirection.asVector();
        for (CartesianPoint point : samples) {
            Vector3 rel = point.subtract(axisOrigin);
            double axialComponent = rel.dot(axisVec);
            Vector3 radialPart = rel.subtract(axisVec.scale(axialComponent));
            maxRadial = Math.max(maxRadial, radialPart.norm());
        }
        return maxRadial;
    }

    /**
     * Returns the closest point on the revolution surface to a given point.
     * Uses sampling approach for revolution surfaces.
     *
     * @param point target point
     * @return approximate closest point on the revolution surface
     */
    public CartesianPoint closestPointTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        CartesianPoint closest = null;
        double minDistance = Double.POSITIVE_INFINITY;

        // Sample at multiple resolutions to find closest point
        for (int resolution : new int[]{16, 32, 64}) {
            java.util.List<java.util.List<CartesianPoint>> grid = sampleGrid(resolution, resolution);
            for (java.util.List<CartesianPoint> row : grid) {
                for (CartesianPoint sample : row) {
                    double dist = point.distanceTo(sample);
                    if (dist < minDistance) {
                        minDistance = dist;
                        closest = sample;
                    }
                }
            }
        }
        return closest != null ? closest : pointAt(0, 0);
    }

    /**
     * Returns the shortest distance from a point to the revolution surface.
     *
     * @param point target point
     * @return approximate shortest distance to the revolution surface
     */
    public double distanceTo(CartesianPoint point) {
        Preconditions.requireNonNull(point, "point");
        return point.distanceTo(closestPointTo(point));
    }
}