package com.minicad.geometry;

import com.minicad.common.Epsilon;
import com.minicad.common.GeometryException;
import com.minicad.common.Preconditions;
import java.util.Objects;

/**
 * Minimal surface of translation representation.
 * Generated by translating a profile curve along a direction vector.
 *
 * @param profile profile curve to be translated
 * @param direction translation direction vector
 */
/**
 * Minimal surface of translation representation.
 * Generated by translating a profile curve along a direction vector.
 *
 * @param profile profile curve to be translated
 * @param direction translation direction vector
 */
public final class SurfaceOfTranslation3 implements SurfaceGeometry {
    private final Curve3 profile;
    private final Vector3 direction;

    public SurfaceOfTranslation3(Curve3 profile, Vector3 direction) {
        this.profile = profile;
        this.direction = direction;
    }

    public Curve3 getProfile() {
        return profile;
    }

    public Vector3 getDirection() {
        return direction;
    }

    // Record-style accessors
    public Curve3 profile() { return getProfile(); }
    public Vector3 direction() { return getDirection(); }

    /**
     * {@inheritDoc}
     *
     * <p>Swept-surface form: {@code P(u, v) = profile(u) + v · direction}.
     * U runs over the profile's natural parameter, V over translation units.</p>
     */
    @Override
    public CartesianPoint pointAt(double u, double v) {
        Preconditions.requireFinite(u, "u");
        Preconditions.requireFinite(v, "v");
        return profile.pointAt(u).add(direction.scale(v));
    }

    /**
     * {@inheritDoc}
     *
     * <p>{@code ∂P/∂u} is the profile tangent and {@code ∂P/∂v} the translation
     * direction, so the normal is their cross product — constant along each
     * ruling of the swept surface.</p>
     */
    @Override
    public Vector3 normalAt(double u, double v) {
        Preconditions.requireFinite(u, "u");
        Preconditions.requireFinite(v, "v");
        return SurfaceGeometry.normalFromTangents(profile.tangentAt(u), direction);
    }

    /**
     * {@inheritDoc}
     *
     * <p>The profile's parameter domain is curve-type-specific (a line has no
     * finite one), so U is swept through {@code Curve3.sample} instead of a
     * guessed range. V is swept over 0..1 translation units.</p>
     */
    @Override
    public java.util.List<java.util.List<CartesianPoint>> sampleGrid(int uSegments, int vSegments) {
        int uCount = Math.max(uSegments, 1);
        int vCount = Math.max(vSegments, 1);
        java.util.List<CartesianPoint> profilePoints =
                new java.util.ArrayList<>(SweptSurfaceSampling.sampleProfile(profile, uCount));
        java.util.List<java.util.List<CartesianPoint>> grid = new java.util.ArrayList<>(profilePoints.size());
        for (CartesianPoint profilePoint : profilePoints) {
            java.util.List<CartesianPoint> row = new java.util.ArrayList<>(vCount + 1);
            for (int iv = 0; iv <= vCount; iv++) {
                row.add(profilePoint.add(direction.scale((double) iv / vCount)));
            }
            grid.add(java.util.List.copyOf(row));
        }
        return java.util.List.copyOf(grid);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SurfaceOfTranslation3 that = (SurfaceOfTranslation3) o;
        return Objects.equals(profile, that.profile) && Objects.equals(direction, that.direction);
    }

    @Override
    public int hashCode() {
        return Objects.hash(profile, direction);
    }

    @Override
    public String toString() {
        return "SurfaceOfTranslation3{" + "profile=" + profile + "direction=" + direction + "}";
    }
}
