package com.minicad.step.model.geometry;

import com.minicad.step.model.core.base.StepEntity;
import java.util.Objects;
/**
 * Resolved RULED_SURFACE.
 * A surface generated by moving a straight line between two directrix curves.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param position placement defining the surface's local coordinate system
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
/**
 * Resolved RULED_SURFACE.
 * A surface generated by moving a straight line between two directrix curves.
 *
 * @param id STEP instance id
 * @param name surface name
 * @param position placement defining the surface's local coordinate system
 * @param directrix1 first directrix curve
 * @param directrix2 second directrix curve
 */
public final class StepRuledSurface implements StepEntity {
    private final int id;
    private final String name;
    private final StepAxis2Placement3D position;
    private final StepEntity directrix1;
    private final StepEntity directrix2;

    public StepRuledSurface(int id, String name, StepAxis2Placement3D position, StepEntity directrix1, StepEntity directrix2) {
        this.id = id;
        this.name = name;
        this.position = position;
        this.directrix1 = directrix1;
        this.directrix2 = directrix2;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepAxis2Placement3D getPosition() {
        return position;
    }

    public StepEntity getDirectrix1() {
        return directrix1;
    }

    public StepEntity getDirectrix2() {
        return directrix2;
    }

    // Record-style accessors
    public int id() { return getId(); }
    public String name() { return getName(); }
    public StepAxis2Placement3D position() { return getPosition(); }
    public StepEntity directrix1() { return getDirectrix1(); }
    public StepEntity directrix2() { return getDirectrix2(); }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepRuledSurface that = (StepRuledSurface) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(position, that.position) && Objects.equals(directrix1, that.directrix1) && Objects.equals(directrix2, that.directrix2);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, position, directrix1, directrix2);
    }

    @Override
    public String toString() {
        return "StepRuledSurface{" + "id=" + id + "name=" + name + "position=" + position + "directrix1=" + directrix1 + "directrix2=" + directrix2 + "}";
    }
}
