package com.minicad.step.model.geometry;

import com.minicad.step.model.base.StepEntity;
import java.util.Objects;
/**
 * Resolved SURFACE_OF_PROJECTION.
 * A surface generated by projecting a profile curve along a direction onto a plane.
 */
/**
 * Resolved SURFACE_OF_PROJECTION.
 * A surface generated by projecting a profile curve along a direction onto a plane.
 */
public final class StepSurfaceOfProjection implements StepEntity {
    private final int id;
    private final String name;
    private final StepEntity profile;
    private final StepEntity projectionDirection;
    private final StepEntity targetPlane;

    public StepSurfaceOfProjection(int id, String name, StepEntity profile, StepEntity projectionDirection, StepEntity targetPlane) {
        this.id = id;
        this.name = name;
        this.profile = profile;
        this.projectionDirection = projectionDirection;
        this.targetPlane = targetPlane;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public StepEntity getProfile() {
        return profile;
    }

    public StepEntity getProjectionDirection() {
        return projectionDirection;
    }

    public StepEntity getTargetPlane() {
        return targetPlane;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        StepSurfaceOfProjection that = (StepSurfaceOfProjection) o;
        return id == that.id && Objects.equals(name, that.name) && Objects.equals(profile, that.profile) && Objects.equals(projectionDirection, that.projectionDirection) && Objects.equals(targetPlane, that.targetPlane);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, profile, projectionDirection, targetPlane);
    }

    @Override
    public String toString() {
        return "StepSurfaceOfProjection{" + "id=" + id + "name=" + name + "profile=" + profile + "projectionDirection=" + projectionDirection + "targetPlane=" + targetPlane + "}";
    }
}
