#!/usr/bin/env python3
"""Re-audit every already-committed instanceof->table fold for missed fall-through.

Why this exists: the folds were generated by a family of one-off scripts, and not
all of them checked whether a branch body actually exits. A branch that falls out
of its `if` keeps testing the *following* ifs in a sequential-if chain; a plain
first-match `return rule.handler()...` loop instead returns that branch's value
immediately. That is a silent behaviour change the compiler, the golden tests and
even a verbatim body-fidelity check cannot see -- the bodies are identical, only
the surrounding control flow differs.

So: for each fold, pull the PRE-fold file from the parent commit, re-extract the
chain with the corrected depth-aware detector, and compare what the chain needed
against the loop shape that actually shipped.

    python tools/audit_folded_dispatch.py

Exit code 0 = every shipped loop matches the semantics its chain required.
"""
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_validate_entity_dispatch import last_statement_exits  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# (label, commit, path, method-signature-prefix, dispatch-variable)
FOLDS = [
    (
        "fold 5  StepCadSolidBuilder.buildSolid",
        "58d183ec",
        "src/main/java/com/minicad/step/semantic/StepCadSolidBuilder.java",
        "    Solid buildSolid(",
        "entity",
    ),
    (
        "fold 6  StepSolidBuilder.buildSolid",
        "ee223634",
        "src/main/java/com/minicad/step/semantic/StepSolidBuilder.java",
        "    Solid buildSolid(",
        "entity",
    ),
    (
        "fold 7  StepShellBuilder.buildShell",
        "e009dbfb",
        "src/main/java/com/minicad/step/semantic/StepShellBuilder.java",
        "    Shell buildShell(",
        "entity",
    ),
    (
        "fold 8  StepDumpApp.validateManagementAssignmentEntity",
        "f3078e23",
        "src/main/java/com/minicad/app/StepDumpApp.java",
        "    private static Integer validateManagementAssignmentEntity(",
        "entity",
    ),
    (
        "fold 9  StepDumpApp.validateProductStructureEntity",
        "bc8fed4d",
        "src/main/java/com/minicad/app/StepDumpApp.java",
        "    private static Integer validateProductStructureEntity(",
        "entity",
    ),
    (
        "fold 10 StepEntityNamingUtils.stepEntityTypeName",
        "866a4435",
        "src/main/java/com/minicad/step/semantic/StepEntityNamingUtils.java",
        "    static String stepEntityTypeName(",
        "entity",
    ),
]

HEADER_RE = re.compile(r"if \((.*)\)\s*\{$")


def show(rev, path):
    out = subprocess.run(
        ["git", "show", rev + ":" + path],
        cwd=ROOT, capture_output=True, text=True,
    )
    if out.returncode != 0:
        raise SystemExit("git show failed for %s:%s\n%s" % (rev, path, out.stderr))
    return out.stdout.replace("\r\n", "\n").replace("\r", "\n").split("\n")


def chain_branches(lines, sig, var):
    start = next(i for i, ln in enumerate(lines) if ln.startswith(sig))
    end = next(i for i in range(start + 1, len(lines)) if lines[i] == "    }")
    prefix = "if (" + var + " instanceof "
    branches = []
    i = start
    while i < end:
        s = lines[i].strip()
        if s.startswith(prefix) and s.endswith("{"):
            cond = HEADER_RE.search(lines[i]).group(1)
            depth = 1
            body = []
            k = i + 1
            while k < end:
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                if depth == 0:
                    break
                body.append(lines[k])
                k += 1
            while body and not body[0].strip():
                body.pop(0)
            while body and not body[-1].strip():
                body.pop()
            branches.append(
                (
                    re.search(r"instanceof (\w+)", cond).group(1),
                    body,
                    "&&" in cond or "||" in cond,
                )
            )
            i = k + 1
            continue
        i += 1
    return branches


def shipped_is_fallthrough(lines, sig):
    """Does the loop that shipped tolerate a null handler result and keep looking?"""
    start = next(i for i, ln in enumerate(lines) if ln.startswith(sig))
    end = next(i for i in range(start + 1, len(lines)) if lines[i] == "    }")
    body = "\n".join(lines[start:end])
    return "!= null" in body


def main():
    problems = 0
    for label, commit, path, sig, var in FOLDS:
        before = show(commit + "~1", path)
        after = show(commit, path)

        branches = chain_branches(before, sig, var)
        falling = [t for t, b, _g in branches if not last_statement_exits(b)]
        guarded = [t for t, _b, g in branches if g]
        needs_fallthrough = bool(falling)
        ships_fallthrough = shipped_is_fallthrough(after, sig)

        status = "OK  "
        if needs_fallthrough and not ships_fallthrough:
            status = "BUG "
            problems += 1
        elif ships_fallthrough and not needs_fallthrough:
            status = "WARN"  # harmless, just a wider loop than required

        print(
            "%s %s\n     branches=%d guarded=%d chain-needs=%s shipped=%s"
            % (
                status,
                label,
                len(branches),
                len(guarded),
                "null-fallthrough" if needs_fallthrough else "first-match",
                "null-fallthrough" if ships_fallthrough else "first-match",
            )
        )
        if falling:
            print("     falls through:", ", ".join(falling))

    print()
    if problems:
        print("AUDIT FAILED: %d fold(s) ship first-match for a chain that needs "
              "fall-through" % problems)
        sys.exit(1)
    print("AUDIT CLEAN: every shipped loop matches the semantics its chain required")


if __name__ == "__main__":
    main()
